name: Docker Build CI

on:
  pull_request:
    branches: [main]
    paths:
      - "config/**"
      - "lib/**"
      - "**.exs"
      - "**.ex"
      - "**.lock"
      - "Dockerfile"
      - ".dockerignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install git
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phineas/lanyard:latest
